### ISSUE TITLE
No results when page name starts with 0

### ISSUE THREAD

**Issue by vineet-goel** [wttech/Sling-Query#5]
Hello,

Problem:
We were getting 0 results for our search in AEM even though the resource is available under the given path. On debugging the issue further, we realised that if the page name starts with '0' then the size of result is zero.
When we use SQL2 query in AEM for searching under the page that starts with 0, that also returns 0 results. And since, Sling-query is also using SQL2 query under the hood, the behavior is expected.

Resolution:
We need to surround the path in the query with single qoutes. For eg:
SELECT \* FROM [nt:base] AS s WHERE ISDESCENDANTNODE(['foo/bar/03'])

I did the testing after making a  change in line 40 of JcrQueryBuilder.java and it worked fine for me.

Please have a look and if possible, provide the new version with the fix.

/Vineet

**Comment by d33t** [comment]
Hi Tomek,
this fix is not included in the sling extension 3.0.0 (release version is from March 2015 and this was fixed back in 2014). I also checked the sling extension repository, but it is not there as well (https://github.com/apache/sling/tree/trunk/contrib/extensions/sling-query).  Why and it is possible to include it? Thanks in advance!

Best regards,
d33t

**Comment by trekawek** [comment]
@d33t, it seems that Oak doesn't support apostrophes-inside-brackets, that's why I had to reverse the [SLING-3971](https://issues.apache.org/jira/browse/SLING-3971) patch. More information can be found on the [mailing list](https://mail-archives.apache.org/mod_mbox/sling-dev/201503.mbox/%3CCADXTASht+R6e3e_q5cqniu-4kzOM=tVa-dxyrZ4pvsDsKYndMQ@mail.gmail.com%3E).

**Comment by d33t** [comment]
@trekawek thanks for your quick response. Ok than just drop the brackets "[]" (e.g. ... WHERE ISDESCENDANTNODE('/some/0path/also-minus-is-problem')), it working on both versions (tested on 5.6.1.SP2 and also on 6.1.0.20150804). According to the specifications you are using brackets only for the selectorName, but not for the path itself or at least I understand it this way:

```
DescendantNode ::= 'ISDESCENDANTNODE(' [selectorName ','] Path ')' 
                   /* If only one selector exists in this query, explicit specification of the selectorName
                      preceding the propertyName is optional */
```
https://docs.jboss.org/jbossdna/latest/manuals/reference/html/jcr-query-and-search.html#d0e7947

**Comment by trekawek** [comment]
Good point. It's fixed in [SLING-5654](https://issues.apache.org/jira/browse/SLING-5654).

**Comment by d33t** [comment]
Thanks for the quick fix. For which date is scheduled the next release? Probably is a good idea to add some tests not just with a path like "/content", but also including some special characters such as digit in front or a minus "-" in the name (the problem I have).
